"""initial schema

Revision ID: 398da4e64f61
Revises: 
Create Date: 2026-05-30 23:43:32.261246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398da4e64f61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('github_url', sa.String(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('default_branch', sa.String(), server_default='main', nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_url')
    )
    op.create_table('file_node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('import_count', sa.Integer(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_complexity', sa.String(), nullable=True),
    sa.Column('ai_role', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'file_path', name='uq_repo_file_path')
    )
    op.create_table('file_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repository.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_edge')
    op.drop_table('file_node')
    op.drop_table('repository')
    # ### end Alembic commands ###
